### PR TITLE
Update 502_GPU.py

### PR DESCRIPTION
**Pull request by howtocodewang**
There are several little mistakes in this file which will make you fail to debug successfully.

### CODE REVIEW

**Comment by howtocodewang** [comment]
@MorvanZhou Yes, I have one GPU that can test the code. I think I have moved all calculation and data into GPU. I didn't record the exact running time. But there is no debug error and the code runs faster than the one without Cuda.

Besides that,  if you use numpy in your code like `print(test_y[:10].numpy(), 'real number')`  which is in the last line. There will be an error `RuntimeError: can't convert CUDA tensor to numpy (it doesn't support GPU arrays). Use .cpu() to move the tensor to host memory first.`So I make some changes in your code based on my test. 

Your Tutorials are very helpful and I have donated by Wechat.

**Comment by MorvanZhou** [comment]
@howtocodewang Thanks for your valuable information and donation. I merged this commit into the mainstream. Hope it would help more people.

**Comment by MorvanZhou** [comment]
@howtocodewang Oh, may I ask is any different between`pred_y = torch.max(test_output, 1)[1].cuda().data.squeeze() ` and `pred_y = torch.max(test_output, 1)[1].data.squeeze() `  when you testing?

**Comment by howtocodewang** [comment]
@MorvanZhou I just test the `pred_y = torch.max(test_output, 1)[1].data.squeeze()` and the code still runs successfully. The reason I wrote `pred_y = torch.max(test_output, 1)[1].cuda().data.squeeze()` is that I want to make sure that `pred_y` and `test_y` are both cuda tensor.  If not, there will be something wrong with this line `accuracy = sum(pred_y == test_y) / test_y.size(0)`.

**Comment by howtocodewang** [comment]
@MorvanZhou I am trying to change some codes into Cuda version.  You use numpy to plot but numpy tensor conflicts with Cuda tensor which is used to accelerate.

**Comment by MorvanZhou** [comment]
@howtocodewang Oh, I see, after the operation `torch.max()` , the `pred_y` becomes an array in CPU, so we cannot compare `pred_y` (in CPU) and `test_y` (in GPU). If this is right, may I ask you to help me to test one more thing? 
Put both `pred_y` and `test_y` in CPU by deleting `cuda()` command and see if this is OK.

**Comment by howtocodewang** [comment]
@MorvanZhou I have made some changes as below:
change `test_y = test_data.test_labels[:2000].cuda()` into `test_y = test_data.test_labels[:2000]`
change `pred_y = torch.max(test_output, 1)[1].cuda().data.squeeze()` into `pred_y = torch.max(test_output, 1)[1].data.squeeze()`

But I got this error.
````
File "/home/XXXXXXXX/PycharmProjects/Learning/Pytorch/Advanced_NN/GPU.py", line 73, in <module>
    accuracy = sum(pred_y == test_y) / test_y.size(0)
TypeError: eq received an invalid combination of arguments - got (torch.LongTensor), but expected one of:
 * (int value)
      didn't match because some of the arguments have invalid types: (!torch.LongTensor!)
 * (torch.cuda.LongTensor other)
      didn't match because some of the arguments have invalid types: (!torch.LongTensor!)
````

This error is the one I have described in my last reply.

**Comment by MorvanZhou** [comment]
Fine, I think it would be better to adopt your edited code. Using cuda everywhere. haha.

**Pull request merged**
